mv "Blank Glass [Stereo mix (WAV)]" "1"
mv "DD_BWJAZZ_90_drum_groove_loop_4_to_the_floor_new_orleans_groove" "2"
mv "Less Mudslide [Stereo mix (WAV)]" "3"
mv "Literally Criminal [Stereo mix (WAV)]" "4"
mv "OLIVER_118_drum_loop_funk_mixready_sweater" "5"
mv "OLIVER_120_drum_loop_disco_for_the_floor_full_G" "6"
mv "sa6_rnbguitar_Cminor_80BPM" "7"
mv "Scream Bloke [Stereo mix (WAV)]" "8"
mv "SIG_C_90_drum_kit_rim_trickle_6-8" "9"
mv "SIG_IH_81_drum_kit_punch_groovin" "10"
mv "Sleeping Friend [Stereo mix (WAV)]" "11"
mv "SOULSURPLUS_elevador_percussion_drum_loop_bossa_nova_jazz_medium_room_3_130bpm" "12"
mv "The Golden Ritual [Stereo mix (WAV)]" "13"
mv "TRKTRN_EBWTLA_115_Acoustic_Guitar_Loop_Full_Mamacita_Fmin" "14"
mv "Veiled Major [Stereo mix (WAV)]" "15"
